CREATE TABLE IF NOT EXISTS `case_files` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(150) NOT NULL,
  `case_identifier` VARCHAR(80) NOT NULL,
  `case_file_title` VARCHAR(180) NOT NULL,
  `description` TEXT NULL,
  `date_created` DATE NOT NULL,
  `client_user_id` INT UNSIGNED NOT NULL,
  `assigned_lawyer_user_id` INT UNSIGNED DEFAULT NULL,
  `status` ENUM('open','ongoing','closed') NOT NULL DEFAULT 'open',
  `folder_name` VARCHAR(180) NOT NULL,
  `attachments_json` LONGTEXT NULL,
  `created_by_user_id` INT UNSIGNED NOT NULL,
  `updated_by_user_id` INT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_case_files_identifier` (`case_identifier`),
  UNIQUE KEY `uq_case_files_folder` (`folder_name`),
  KEY `idx_case_files_fullname` (`full_name`),
  KEY `idx_case_files_title` (`case_file_title`),
  KEY `idx_case_files_client` (`client_user_id`),
  KEY `idx_case_files_lawyer` (`assigned_lawyer_user_id`),
  CONSTRAINT `fk_case_files_client_user` FOREIGN KEY (`client_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_case_files_assigned_lawyer_user` FOREIGN KEY (`assigned_lawyer_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_files_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_case_files_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `case_file_folders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `case_file_id` INT UNSIGNED NOT NULL,
  `parent_folder_id` INT UNSIGNED DEFAULT NULL,
  `name` VARCHAR(150) NOT NULL,
  `slug` VARCHAR(170) NOT NULL,
  `created_by_user_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_case_file_folder_slug` (`case_file_id`, `slug`),
  KEY `idx_case_file_folders_case` (`case_file_id`),
  KEY `idx_case_file_folders_parent` (`parent_folder_id`),
  CONSTRAINT `fk_case_file_folders_case` FOREIGN KEY (`case_file_id`) REFERENCES `case_files` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_case_file_folders_parent` FOREIGN KEY (`parent_folder_id`) REFERENCES `case_file_folders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_case_file_folders_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `case_file_documents` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `case_file_id` INT UNSIGNED NOT NULL,
  `folder_id` INT UNSIGNED NOT NULL,
  `original_name` VARCHAR(255) NOT NULL,
  `stored_name` VARCHAR(255) NOT NULL,
  `mime_type` VARCHAR(120) DEFAULT NULL,
  `file_size` INT UNSIGNED DEFAULT NULL,
  `file_hash` CHAR(64) DEFAULT NULL,
  `upload_status` ENUM('pending','approved','rejected') NOT NULL DEFAULT 'approved',
  `uploaded_by_user_id` INT UNSIGNED NOT NULL,
  `approved_by_user_id` INT UNSIGNED DEFAULT NULL,
  `approved_at` DATETIME DEFAULT NULL,
  `rejection_reason` TEXT DEFAULT NULL,
  `is_confidential` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_case_file_documents_stored` (`case_file_id`, `stored_name`),
  KEY `idx_case_file_documents_case` (`case_file_id`, `upload_status`),
  KEY `idx_case_file_documents_folder` (`folder_id`),
  KEY `idx_case_file_documents_uploaded_by` (`uploaded_by_user_id`),
  CONSTRAINT `fk_case_file_documents_case` FOREIGN KEY (`case_file_id`) REFERENCES `case_files` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_case_file_documents_folder` FOREIGN KEY (`folder_id`) REFERENCES `case_file_folders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_case_file_documents_uploaded_by` FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_case_file_documents_approved_by` FOREIGN KEY (`approved_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
