CREATE TABLE IF NOT EXISTS `manual_payments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` INT UNSIGNED NOT NULL,
  `payment_channel` ENUM('gcash') NOT NULL DEFAULT 'gcash',
  `payment_for` VARCHAR(180) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'PHP',
  `payer_name` VARCHAR(150) NOT NULL,
  `payer_contact` VARCHAR(40) DEFAULT NULL,
  `reference_number` VARCHAR(120) DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `proof_original_name` VARCHAR(255) NOT NULL,
  `proof_stored_name` VARCHAR(255) NOT NULL,
  `proof_mime_type` VARCHAR(120) DEFAULT NULL,
  `proof_size` INT UNSIGNED DEFAULT NULL,
  `status` ENUM('pending','verified','rejected') NOT NULL DEFAULT 'pending',
  `admin_notes` TEXT DEFAULT NULL,
  `reviewed_by_user_id` INT UNSIGNED DEFAULT NULL,
  `reviewed_at` DATETIME DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_manual_payments_client` (`client_id`, `status`, `created_at`),
  KEY `idx_manual_payments_status` (`status`, `created_at`),
  KEY `idx_manual_payments_reviewer` (`reviewed_by_user_id`),
  CONSTRAINT `fk_manual_payments_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_manual_payments_reviewer` FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
